# Generated by Django 4.0 on 2022-01-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(default='Student', max_length=100)),
                ('description', models.CharField(default='', max_length=256)),
                ('achievements', models.CharField(default='', max_length=256)),
                ('github', models.CharField(default='', max_length=100)),
                ('linkedin', models.CharField(default='', max_length=100)),
                ('isverified', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
