# Generated by Django 4.0.6 on 2022-12-23 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('message', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='councilMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.URLField(blank=True)),
                ('council', models.CharField(choices=[('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('order_number', models.IntegerField(blank=True, default=0)),
                ('insta_id', models.URLField(blank=True)),
                ('linked_in', models.URLField(blank=True)),
                ('email', models.URLField(blank=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, null=True)),
                ('council', models.CharField(choices=[('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('order_number', models.IntegerField(blank=True, default=0)),
                ('insta_id', models.URLField(blank=True)),
                ('linked_in', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phoneNumber', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='editorials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorial_name', models.CharField(max_length=100)),
                ('editorial_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('poster', models.ImageField(upload_to='events/eventPosters')),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Other', 'Other')], max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gallary_pic1', models.ImageField(upload_to='events/eventsGallary')),
                ('gallary_pic2', models.ImageField(upload_to='events/eventsGallary')),
                ('gallary_pic3', models.ImageField(upload_to='events/eventsGallary')),
                ('gallary_pic4', models.ImageField(upload_to='events/eventsGallary')),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(default='Student', max_length=100)),
                ('description', models.CharField(default='', max_length=256)),
                ('achievements', models.CharField(default='', max_length=256)),
                ('github', models.CharField(default='', max_length=100)),
                ('linkedin', models.CharField(default='', max_length=100)),
                ('isverified', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
