# Generated by Django 4.0.6 on 2022-12-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='councilmembers',
            name='phoneNumber',
        ),
        migrations.RemoveField(
            model_name='developers',
            name='phoneNumber',
        ),
    ]
