# Generated by Django 4.0.6 on 2022-12-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_councilmembers_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='councilmembers',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='developers',
            name='image',
        ),
        migrations.AddField(
            model_name='councilmembers',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='developers',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
