# Generated by Django 4.0.6 on 2022-09-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('message', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
