# Generated by Django 4.0.6 on 2022-12-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_councilmembers_photo_remove_developers_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilmembers',
            name='photo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='developers',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
