# Generated by Django 4.0.6 on 2022-12-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_councilmembers_photo_developers_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='events2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('poster1', models.URLField(blank=True)),
                ('poster2', models.URLField(blank=True)),
                ('poster3', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Other', 'Other')], max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gallary_pic1_link', models.URLField(blank=True)),
                ('gallary_pic2_link', models.URLField(blank=True)),
                ('gallary_pic3_link', models.URLField(blank=True)),
                ('gallary_pic4_link', models.URLField(blank=True)),
            ],
        ),
    ]
