# Generated by Django 4.0.6 on 2022-10-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_editorials'),
    ]

    operations = [
        migrations.CreateModel(
            name='developers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('council', models.CharField(choices=[('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('order_number', models.IntegerField(blank=True, default=0)),
                ('insta_id', models.URLField(blank=True)),
                ('linked_in', models.URLField(blank=True)),
                ('email', models.URLField(blank=True)),
            ],
        ),
    ]
