# Generated by Django 4.0.6 on 2022-12-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_events2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilmembers',
            name='council',
            field=models.CharField(choices=[('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE'), ('FACULTY ADVISORS ', 'FACULTY ADVISORS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='developers',
            name='council',
            field=models.CharField(choices=[('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE'), ('FACULTY ADVISORS ', 'FACULTY ADVISORS')], max_length=100),
        ),
    ]
