# Generated by Django 4.0.6 on 2022-10-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_photo_developers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='developers',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
