# Generated by Django 4.0.6 on 2022-12-23 16:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_councilmembers_council_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='description',
        ),
        migrations.AddField(
            model_name='appuser',
            name='isMember',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
