# Generated by Django 4.0.6 on 2022-12-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_appuser_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='github',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='linkedin',
            field=models.URLField(default='', max_length=100),
        ),
    ]
