# Generated by Django 4.0.6 on 2022-11-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_councilmembers'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('poster', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Other', 'Other')], max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('gallary_pic1', models.ImageField(upload_to='events/eventsGallary')),
                ('gallary_pic2', models.ImageField(upload_to='events/eventsGallary')),
                ('gallary_pic3', models.ImageField(upload_to='events/eventsGallary')),
                ('gallary_pic4', models.ImageField(upload_to='events/eventsGallary')),
            ],
        ),
    ]
