# Generated by Django 4.0.6 on 2022-12-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_appuser_github_alter_appuser_linkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developers',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='developers',
            name='last_name',
        ),
    ]
