# Generated by Django 4.0.6 on 2022-12-25 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_first_name_developers_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event',
        ),
    ]
