# Generated by Django 4.0.6 on 2022-11-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_gallery_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery_2',
            old_name='poster',
            new_name='gallary_pic1_link',
        ),
        migrations.RemoveField(
            model_name='gallery_2',
            name='gallary_pic1',
        ),
        migrations.RemoveField(
            model_name='gallery_2',
            name='gallary_pic2',
        ),
        migrations.RemoveField(
            model_name='gallery_2',
            name='gallary_pic3',
        ),
        migrations.RemoveField(
            model_name='gallery_2',
            name='gallary_pic4',
        ),
        migrations.AddField(
            model_name='gallery_2',
            name='gallary_pic2_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gallery_2',
            name='gallary_pic3_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gallery_2',
            name='gallary_pic4_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gallery_2',
            name='poster_link',
            field=models.URLField(blank=True),
        ),
    ]
