# Generated by Django 4.0.6 on 2022-12-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_delete_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='councilmembers',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='councilmembers',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='councilmembers',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
