# Generated by Django 4.0 on 2022-11-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_poster_gallery_2_gallary_pic1_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery_2',
            old_name='gallary_pic1_link',
            new_name='gallary_pic1',
        ),
        migrations.RenameField(
            model_name='gallery_2',
            old_name='gallary_pic2_link',
            new_name='gallary_pic2',
        ),
        migrations.RenameField(
            model_name='gallery_2',
            old_name='gallary_pic3_link',
            new_name='gallary_pic3',
        ),
        migrations.RenameField(
            model_name='gallery_2',
            old_name='gallary_pic4_link',
            new_name='gallary_pic4',
        ),
        migrations.RenameField(
            model_name='gallery_2',
            old_name='poster_link',
            new_name='poster',
        ),
    ]
