# Generated by Django 4.0.6 on 2022-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_poster_gallery_2_gallary_pic1_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery_2',
            old_name='poster_link',
            new_name='poster1',
        ),
        migrations.AddField(
            model_name='gallery_2',
            name='poster2',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='gallery_2',
            name='poster3',
            field=models.URLField(blank=True),
        ),
    ]
