# Generated by Django 4.0.6 on 2022-11-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_rename_gallary_pic1_link_gallery_2_gallary_pic1_and_more'),
        ('backend', '0011_rename_poster_link_gallery_2_poster1_and_more'),
    ]

    operations = [
    ]
