# Generated by Django 3.1.7 on 2023-03-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20230312_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingWorkshopmodels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=100)),
                ('PosterImage', models.URLField(blank=True, null=True)),
                ('FormLink', models.URLField(blank=True)),
                ('Description', models.TextField()),
                ('start_date', models.DateField()),
            ],
        ),
    ]
