# Generated by Django 3.1.7 on 2023-03-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_upcomingworkshopmodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingworkshopmodels',
            name='start_date',
        ),
        migrations.AddField(
            model_name='upcomingworkshopmodels',
            name='DurationDate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='upcomingworkshopmodels',
            name='EventName',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
