# Generated by Django 3.1.7 on 2023-03-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_auto_20230312_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='product_image')),
                ('Small_Specs', models.CharField(max_length=254)),
                ('Info', models.TextField()),
                ('Is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
