# Generated by Django 3.1.7 on 2023-03-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_component'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image',
            field=models.URLField(default='https://drive.google.com/uc?export=download&id=1BS738bM50KPliEbb7o30rDfDuvxCS_rL'),
        ),
    ]
