# Generated by Django 3.1.7 on 2023-04-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_auto_20230313_0104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(blank=True, max_length=500)),
                ('PosterImage', models.URLField(blank=True, null=True)),
                ('InitiativesLink', models.URLField(blank=True)),
                ('Description', models.TextField()),
            ],
        ),
    ]
