# Generated by Django 3.1.7 on 2023-04-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_councilurl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='councilurl',
            new_name='DevelopersURL',
        ),
    ]
