# Generated by Django 3.1.7 on 2023-04-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20230407_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developersurl',
            name='council',
        ),
    ]
