# Generated by Django 3.1.7 on 2023-04-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_remove_developersurl_council'),
    ]

    operations = [
        migrations.AddField(
            model_name='events2',
            name='order_number',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
