# Generated by Django 3.1.7 on 2023-04-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_image/profile1.png', null=True, upload_to='profile_image'),
        ),
    ]
