# Generated by Django 3.1.7 on 2023-04-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_auto_20230408_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='councilmembers',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='developers',
            name='image',
        ),
        migrations.RemoveField(
            model_name='events2',
            name='gallary_pic1_link',
        ),
        migrations.RemoveField(
            model_name='events2',
            name='gallary_pic2_link',
        ),
        migrations.RemoveField(
            model_name='events2',
            name='gallary_pic3_link',
        ),
        migrations.RemoveField(
            model_name='events2',
            name='gallary_pic4_link',
        ),
        migrations.RemoveField(
            model_name='events2',
            name='poster1',
        ),
        migrations.RemoveField(
            model_name='events2',
            name='poster2',
        ),
        migrations.RemoveField(
            model_name='events2',
            name='poster3',
        ),
        migrations.RemoveField(
            model_name='upcomingworkshopmodels',
            name='PosterImage',
        ),
    ]
