# Generated by Django 3.1.7 on 2023-04-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20230408_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events2',
            name='gallary_pic1_link',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='events2',
            name='gallary_pic2_link',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='events2',
            name='gallary_pic3_link',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='events2',
            name='gallary_pic4_link',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='events2',
            name='poster1',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='events2',
            name='poster2',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='events2',
            name='poster3',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
        migrations.AlterField(
            model_name='upcomingworkshopmodels',
            name='PosterImage',
            field=models.ImageField(blank=True, null=True, upload_to='UpcomingEvents'),
        ),
    ]
