# Generated by Django 3.1.7 on 2023-04-09 12:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_component_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusernonmember',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
