# Generated by Django 3.1.7 on 2023-04-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_auto_20230410_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(blank=True, default='9999999990', max_length=13, null=True),
        ),
    ]
