# Generated by Django 3.1.7 on 2023-04-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_auto_20230410_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='github',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='linkedin',
        ),
    ]
