# Generated by Django 3.1.7 on 2023-04-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_auto_20230410_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='certificates',
        ),
    ]
