# Generated by Django 3.1.7 on 2023-04-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_remove_certificates_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='certificates',
            field=models.ImageField(blank=True, null=True, upload_to='certificates'),
        ),
    ]
